### ISSUE TITLE
[Bug]: Had 14mil in cash, re logged and came back in with no cash

### ISSUE THREAD

**Issue by dbixoxo** [lunastudiosuk/issue-tracker#3]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hello, i was going to Paleto Casino and when i withdrew my cash i went to go buy chips. I noticed that the place you would usually buy chips at werent showing so i decided to re log. After loading back in i had £0 in cash and £50,000 in my bank

### Expected behaviour

Cash stays the same

### Steps to reproduce

1. go into Paleto casino
2. withdrew money
3. Re-log

### Any Texture Packs? (If so list)

none

### LUNA User ID

14

**Comment by kerft** [comment]
Im having a look at this, Bare with me and i'll get back to you

**Comment by kerft** [comment]
This issue has long been resolved
