### ISSUE TITLE
[Bug]: Paleto Casini, Nowhere to buy chips

### ISSUE THREAD

**Issue by dbixoxo** [lunastudiosuk/issue-tracker#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Nowhere to buy chips in Paleto Casino

### Expected behaviour

A place to buy chips

### Steps to reproduce

1. go into paleto casino
2. goto what should be the place to buy chips

### Any Texture Packs? (If so list)

no

### LUNA User ID

14

**Comment by kerft** [comment]
I have since added this location
