### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Paul5m** [lunastudiosuk/issue-tracker#5]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

simeons garage on the path , nd  rebel diner name says … trader instead of Luna trader or pops diner other than them I have encountered so far brilliant server

### Expected behaviour

.

### Steps to reproduce

.

### Any Texture Packs? (If so list)

reshade

### LUNA User ID

22

**Comment by kerft** [comment]
Trader sign sorted, Simeons garage location has been moved back
